server:
  port: 8888
spring:
  application:
    name: matt-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fabiovmat/matt-cfg-server
          #username: 
          #password: 
          default-label: main
          search-paths:
          - 'greeting-service*'
  